source_dir = "site"
dest_dir = "public"
grammar_dir = "grammars"
layout_dir = "layouts"
partial_dir = "partials"
agda_dir = "lagda"
exclude = ["*.agdai"]

[[taxonomies]]
name = "categories"
template = "tag.jingoo"

[[taxonomies]]
name = "tags"
template = "tag.jingoo"
