name: install-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ocaml-compiler:
          - 4.13.x
          - 4.14.x
          - 5.0.x
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Update path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          eval $(opam env)
          sudo apt-get install agda-bin
          sudo apt-get install libonig-dev
          pip3 install agda-pkg
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          apkg init
          apkg install standard-library --version v1.1 --yes
          opam install . --with-test
          dune fmt
          cd example
          camyll build
          cd ../web
          camyll build
